name: Bug report
description: Report a bug in this project
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/FormidableLabs/.github/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: input
    attributes:
      label: Code Sandbox link
      description: |
        Please include a code sandbox link or a similar reproduction if possible.
        Issues with sandbox links are typically resolved faster.

  - type: textarea
    attributes:
      render: markdown
      label: Bug report
      description: |
        A clear and concise description of what the bug is. Please include any
        screenshots or code snippets that may help us understand the issue.
    validations:
      required: true
